### ISSUE TITLE
Suggestion for new format in Jobs destination call and variable packaging.

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#116]
I propose that we go about a more intuitive approach with the destination field. I propose that similarly to how we handle multiple variable returns, we should handle destinations that same way with contracts to functions. Currently we need to do something like this:

```
jobs:

- name: deployC
  job:
    deploy:
      contract: array.sol
      wait: true

- name: callJobWithFunction
  job:
    call:
      destination: $deployC
      data: deployCFunction someData
      wait: true
```

I think we should rather do something like this:

```
jobs:

- name: deployC
  job:
    deploy:
      contract: array.sol
      wait: true

- name: callJobWithFunction
  job:
    call:
      destination: $deployC.deployCFunction
      data: someData
      wait: true
```

Furthermore, I think the way we structure the data should be handled differently. I think each data input should have its own column, such like this:

```
jobs:

- name: deployC
  job:
    deploy:
      contract: array.sol
      wait: true

- name: callJobWithFunction
  job:
    call:
      destination: $deployC.deployCFunction
      data:
         - 1
         - aString
         - [this, is, an, array]
      wait: true
```

I think this format will be: 

1. More readable
2. It will allow us to better compartmentalize types going forward.
3. I think it better aligns with the ABI. 

Would love to get your thoughts on this, @compleatang

**Comment by compleatang** [comment]
I like this idea with one change.

```yaml
jobs:

- name: deployC
  job:
    deploy:
      contract: array.sol
      wait: true

- name: callJobWithFunction
  job:
    call:
      destination: $deployC
      function: deployCFunction
      data:
         - 1
         - aString
         - [this, is, an, array]
      wait: true
```

overall this will make it more verbose, but it will make wrangling the types a lot easier.

this will be a breaking change (it will break a lot of folks' code) so we need to schedule it for 0.12.0 when we can implement breaking changes rather than upcoming release (0.11.5).
