### ISSUE TITLE
[Core] Struct instantiation in an epm.yaml

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#123]
Structs currently do not work with the epm yaml, nor would it work with Solidity, but for when they do, I think this is the format that we should go with (when struct is an object in the ABI):

```
- name: callJobWithFunction
  job:
    call:
      destination: $deployC
      function: deployCFunction
      data:
         - {1, "string", 2, "anotherString"} #this would represent a struct with in order int, string, int, string as its traits
```
