### ISSUE TITLE
[Core] `source` in call and query-contract jobs should be changed to `as`

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-pm#172]
Rather than:

```
- name: switchToAccountName
  job:
    account:
      address: $accountName

- name: doSomething
  job:
    call:
      destination: $someContract
      data: someCall
      abi: someContract
      wait: true
```

Proposal:

```
- name: doSomething
  job:
    call:
      destination: $someContract
      as: $accountName
      data: someCall
      abi: someContract
      wait: true
```

`as: ` should only be necessary for deploy and call jobs.

You'll especially appreciate this when having to switch accounts often.
