### ISSUE TITLE
[Tests] Add integration testing for all paths for contracts, etc. that eris-pm utilizes via eris-cli

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#196]
Given the following directory and contract setup:

`/users/X/workspace/project/` => root
`$root/contracts/Mappings.sol`
`$root/contract_bundles/erisindustries/common-base/BaseErrors.sol`
`$root/test/fixtures/MappingLib/epm.yaml`

The epm.yaml has the following content:
```
jobs:
- name: BaseErrorsLib
  job:
    deploy:
      contract: contract_bundles/erisindustries/commons-base/BaseErrors.sol
      wait: true

- name: MappingsLib
  job:
    deploy:
      contract: contracts/Mappings.sol
      libraries: BaseErrors:$BaseErrorsLib
      wait: true
```

The `MappingsLib.sol` contains an import statement:
`import "contract_bundles/erisindustries/commons-base/BaseErrors.sol";`

The following command is executed with the $root project folder as the start directory to look for contracts:
```
eris pkgs do -c test -a CDB00407B6EDBF6735A88AA5B34FA24A8984D421 -l http://172.17.0.2:9099 -p "/Users/X/workspace/project"
Performing action. This can sometimes take a wee while.
Executing Job                                 defaultAddr
Executing Job                                 BaseErrorsLib
Deploying Contract                       name=BaseErrors
                                         addr=EFEB89F134AD375A0F8FEBB138B928788085CE96
Executing Job                                 MappingsLib
failed to read include file open contracts/contracts/contract_bundles/erisindustries/commons-base/BaseErrors.sol: no such file or directory
ERR!:Failed to read include file: open contracts/contracts/contract_bundles/erisindustries/commons-base/BaseErrors.sol: no such file or directory
Error compiling contracts
:65:20: Error: Undeclared identifier.
            return BaseErrors.RESOURCE_ALREADY_EXISTS();
                   ^--------^
```

As can be seen, the paths in the epm.yaml are resolved correctly using the $root project dir as starting point. Both .sol files are found for deployment.
However, the import statement inside the `Mappings.sol` file results in an unexpected path assembly and error:
`open contracts/contracts/contract_bundles/erisindustries/commons-base/BaseErrors.sol: no such file or directory`

Versions:
```
OSX version: 10.11.6
Eris CLI Version: 0.12.0-rc3
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
docker-machine version 0.7.0, build a650a40
```
