### ISSUE TITLE
address parameters always 0

### ISSUE THREAD

**Issue by arrivets** [eris-ltd/eris-pm#32]
Hello,

whenever I use epm to call a contract method that takes a parameter of type address, the parameter in the call-data is always set to 0.

For example, here is the contract I am trying to test with epm:
```
contract IdisContractsFTW {
  address storedAddress;

  function set(address x) {
    storedAddress = x;
  }

  function get() constant returns (address retVal) {
    return storedAddress;
  }

}
```
and the epm.yaml:

```
jobs:

- name: account
  job:
    account:
      address: 3F1861698CE1EC9DED051754AB211D6523637B4F

- name: setStorage
  job:
    set:
      val: 666661698CE1EC9DED051754AB211D6523637B4F

- name: deployStorageK
  job:
    deploy:
      contract: idi.sol
      wait: true

- name: setStorage
  job:
    call:
      destination: $deployStorageK
      data: set $setStorage
      wait: true

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      data: get

- name: assertStorage
  job:
    assert:
      key: $queryStorage
      relation: eq
      val: $setStorage
```

And here is what the epm logs say for the setStorage job:
```
Executing Job Named =>		setStorage
	Type =>			Call
Fixing Variables =>		$deployStorageK:38EA42CE0F563DAC06301D859C2CBF0432238039
ABI Spec =>			{map[get:get() set:set(address)]}
Fixing Variables =>		$setStorage:666661698CE1EC9DED051754AB211D6523637B4F
Calling =>			38EA42CE0F563DAC06301D859C2CBF0432238039:2801617e0000000000000000000000000000000000000000000000000000000000000000
```

So the address parameter is always set to 0000000000000000000000000000000000000000000000000000000000000000 although I provided something else. This happens also when the parameter is specified directly ( as opposed to through a variable) 

Is there a special way to use parameters of type address?

Thanks
