### ISSUE TITLE
use a tx struct

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#6]
```
      to: $NameCoin
      sig: register:[int256,int256]:int256
      data:
        - $Subcurrency
        - SubcurrencyName
      gas: 100000
      gas_price: 10000000000000
      value: 0
      retry: 30
      wait: True
```

will need monk types and some receiver for those.
