### ISSUE TITLE
Boolean string are not properly parsed from data field

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-pm#71]
if we have an epm job like:
```
- name: setBool
  job:
    call:
      destination: $deployStorageK
      data: set true
      wait: true
```
The "true" value is not correctly parse. Not sure if this is an issue on eris-abi side or eris-pm. It does work if a variable is set with the value true and then used or if the value 1 is passed but the true string here does not seem to be getting parse.

Will update app06 for testing usage of passed arguments as well as set variables.

Thanks to @kootenpv for helping narrow this one down!
