### ISSUE TITLE
enable running of arbitrary mocha commands

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#90]
```yaml
job:
  mocha:
     file: my_crappy.js
```

job result should just be `true` (and it should error if the mocha exits != 0)
